apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim 
  labels:
    app: mongo
    tier: database
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi    